- name: frontend
  hosts: WEB
  become: true
  tasks:
    - name: install ngnix
      ansible.builtin.package:
        name: nginx
        state: latest

    - name: run ngnix
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes